### ISSUE TITLE
Can not configure API_KEY=<your key> in a .env file

### ISSUE THREAD

**Issue by M0dred** [gf13579/splunk_easm_worker#15]
Can not find these comments

# configure API_KEY=<your key> in a .env file
# optionally, edit splunk_easm_worker/subfinder-provider-config.yaml

**Comment by gf13579** [comment]
Sorry - step-by-step documentation is on its way.

subfinder-provider-config.yaml doesn't need to exist, but you can choose to populate it with API keys for common OSINT sources to improve discovery. See https://github.com/projectdiscovery/subfinder/blob/main/README.md#post-installation-instructions for an example.

For the API_KEY - used by Splunk to communicate with the worker, just create a .env file in the root folder i.e. the same one as the docker-compose.yml file, which references the .env file.
